export const ColorList = [
  {
    name: "Cyan-Primary",
    startColor: "#15AABF",
    endColor: "#15AABF80",
    hover: "",
  },
  {
    name: "Red-Primary",
    startColor: "#FA5252",
    endColor: "#FA525280",
    hover: "",
  },
  {
    name: "Teal-Primary",
    startColor: "#12B886",
    endColor: "#12B88680",
    hover: "",
  },
  {
    name: "Pink-Primary",
    startColor: "#E64980",
    endColor: "#E6498080",
    hover: "",
  },
  {
    name: "Brand-Primary",
    startColor: "#208D8E",
    endColor: "#208D8E80",
    hover: "#25a2a3",
  },
  {
    name: "Grape-Primary",
    startColor: "#BE4BDB",
    endColor: "#BE4BDB80",
    hover: "",
  },
  {
    name: "Green-Primary",
    startColor: "#40C057",
    endColor: "#40C05780",
    hover: "",
  },
  {
    name: "Violet-Primary",
    startColor: "#7950F2",
    endColor: "#7950F280",
    hover: "",
  },
  {
    name: "Lime-Primary",
    startColor: "#82C91E",
    endColor: "#82C91E80",
    hover: "",
  },
  {
    name: "Indigo-Primary",
    startColor: "#4C6EF5",
    endColor: "#4C6EF580",
    hover: "",
  },
  {
    name: "Yellow-Primary",
    startColor: "#FAB005",
    endColor: "#FAB00580",
    hover: "",
  },
  {
    name: "Blue-Primary",
    startColor: "#228BE6",
    endColor: "#228BE680",
    hover: "",
  },
  {
    name: "Orange-Primary",
    startColor: "#FD7E14",
    endColor: "#FD7E1480",
    hover: "",
  },
];
